"""initial schema: brands, drafts, variants, approvals, schedules, engagement

Revision ID: 0001
Revises:
Create Date: 2026-09-06

Hand-written rather than autogenerated -- autogenerate compares against a live
database, and there was none when the schema was first written. Verified
instead by rendering this migration's DDL offline and diffing it against the
DDL of `app.store.models.Base.metadata`; `tests/test_migrations.py` keeps that
true on every run.

A frozen snapshot, not a mirror. Later edits to the models arrive as new
revisions, and nothing here imports from app.store.models -- a migration that
followed the live models would silently change meaning as they changed.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Spelled out rather than imported from app.domain.states, for the reason in the
# docstring: this records what the schema was on the day it ran.
_DRAFT_STATES = ("draft", "pending_approval", "approved", "rejected")
_SCHEDULE_STATES = (
    "scheduled",
    "publishing",
    "published",
    "failed",
    "dead_letter",
    "cancelled",
)
_VERDICTS = ("approved", "edited", "rejected", "timeout")

# The verdicts that let a post through, and the states in which a scheduled post
# still occupies its variant. Both mirror sets in app.domain.states.
_APPROVING = "'approved', 'edited'"
_OCCUPYING = "'failed', 'published', 'publishing', 'scheduled'"

_NOW = sa.text("now()")


def _enum(*values: str) -> sa.Enum:
    """A VARCHAR, not a Postgres ENUM type.

    A Postgres enum cannot have a value removed, and adding one is a different
    and more locking operation than rewriting a CHECK constraint.

    The CHECK itself is declared separately by `_check` rather than generated
    here: a type-bound constraint is invisible to Alembic's comparison, which
    then reports it as drift and offers to drop it.
    """
    return sa.Enum(*values, native_enum=False, create_constraint=False)


def _check(column: str, values: tuple[str, ...], name: str) -> sa.CheckConstraint:
    rendered = ", ".join(f"'{value}'" for value in values)
    return sa.CheckConstraint(f"{column} IN ({rendered})", name=name)


def _json() -> postgresql.JSONB:
    return postgresql.JSONB(astext_type=sa.Text())


def upgrade() -> None:
    op.create_table(
        "brands",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False
        ),
        sa.PrimaryKeyConstraint("slug"),
    )

    op.create_table(
        "drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("brand_slug", sa.String(length=64), nullable=False),
        sa.Column("concept", sa.Text(), nullable=False),
        sa.Column("angle", sa.String(length=64), nullable=True),
        sa.Column("thread_id", sa.String(length=128), nullable=True),
        sa.Column("state", _enum(*_DRAFT_STATES), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False
        ),
        sa.ForeignKeyConstraint(["brand_slug"], ["brands.slug"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        _check("state", _DRAFT_STATES, "ck_drafts_state"),
    )
    op.create_index(op.f("ix_drafts_brand_slug"), "drafts", ["brand_slug"])
    op.create_index(op.f("ix_drafts_thread_id"), "drafts", ["thread_id"])
    # The analytical dimension: "which kinds of post work" (FR-4) groups by this.
    op.create_index(op.f("ix_drafts_angle"), "drafts", ["angle"])

    op.create_table(
        "post_variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("brand_slug", sa.String(length=64), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("media", _json(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False
        ),
        sa.ForeignKeyConstraint(["brand_slug"], ["brands.slug"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["draft_id"], ["drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # One brief produces one post per platform: the structural form of the
        # in-memory guard app.main keeps across gate hits.
        sa.UniqueConstraint("draft_id", "platform", name="uq_variant_draft_platform"),
    )
    op.create_index(
        op.f("ix_post_variants_brand_slug"), "post_variants", ["brand_slug"]
    )

    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("brand_slug", sa.String(length=64), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("decision", _enum(*_VERDICTS), nullable=False),
        sa.Column("approver", sa.String(length=64), nullable=True),
        sa.Column("approved_body", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "decided_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False
        ),
        sa.ForeignKeyConstraint(["brand_slug"], ["brands.slug"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["post_variants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        # The target of scheduled_posts' composite foreign key. Postgres needs a
        # unique constraint on the referenced columns, and (id) alone will not
        # do: the decision has to travel with the id for the CHECK on the other
        # side to have anything to test.
        sa.UniqueConstraint("id", "decision", name="uq_approval_id_decision"),
        _check("decision", _VERDICTS, "ck_approvals_decision"),
    )
    op.create_index(op.f("ix_approvals_brand_slug"), "approvals", ["brand_slug"])

    op.create_table(
        "scheduled_posts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("brand_slug", sa.String(length=64), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("approval_id", sa.Uuid(), nullable=False),
        sa.Column("approval_decision", _enum(*_VERDICTS), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", _enum(*_SCHEDULE_STATES), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("external_url", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False
        ),
        sa.ForeignKeyConstraint(["brand_slug"], ["brands.slug"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["post_variants.id"], ondelete="RESTRICT"
        ),
        # C-1 and FR-8 in SQL. The pair points at one approvals row AND carries
        # its decision; the CHECK then refuses any decision that is not an
        # approval. Either alone has a hole -- the FK would accept a rejection,
        # the CHECK would accept a decision matching no row.
        sa.ForeignKeyConstraint(
            ["approval_id", "approval_decision"],
            ["approvals.id", "approvals.decision"],
            name="fk_scheduled_post_approved",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            f"approval_decision IN ({_APPROVING})",
            name="ck_scheduled_post_actually_approved",
        ),
        _check("state", _SCHEDULE_STATES, "ck_scheduled_posts_state"),
        _check(
            "approval_decision", _VERDICTS, "ck_scheduled_posts_approval_decision"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_posts_brand_slug"), "scheduled_posts", ["brand_slug"]
    )
    # The publisher's claim query: due rows in a claimable state, oldest first.
    op.create_index(
        "ix_scheduled_post_due", "scheduled_posts", ["state", "scheduled_for"]
    )
    # FR-13. One live schedule per variant -- queued, publishing and already
    # published all count. Partial, so a cancelled or dead-lettered attempt
    # frees the variant for a genuine retry.
    op.create_index(
        "uq_live_schedule_per_variant",
        "scheduled_posts",
        ["variant_id"],
        unique=True,
        postgresql_where=sa.text(f"state IN ({_OCCUPYING})"),
    )
    # Second line of defence: if a retry did land a duplicate, the two rows
    # cannot both record an external id.
    op.create_index(
        "uq_scheduled_post_external_id",
        "scheduled_posts",
        ["platform", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )

    # --- what happened after it went out (FR-4, FR-16) ---------------------

    op.create_table(
        "post_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("brand_slug", sa.String(length=64), nullable=False),
        sa.Column("scheduled_post_id", sa.Uuid(), nullable=False),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=_NOW,
            nullable=False,
        ),
        # All nullable: no platform reports all of these, and a zero would be a
        # lie about a metric that was never returned.
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("reach", sa.Integer(), nullable=True),
        sa.Column("reactions", sa.Integer(), nullable=True),
        sa.Column("comments", sa.Integer(), nullable=True),
        sa.Column("shares", sa.Integer(), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("saves", sa.Integer(), nullable=True),
        sa.Column("video_views", sa.Integer(), nullable=True),
        # The platform's own response, unmodelled -- the per-reaction-type
        # breakdown, watch time, and whatever the next platform invents.
        sa.Column("raw", _json(), nullable=False),
        sa.ForeignKeyConstraint(["brand_slug"], ["brands.slug"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["scheduled_post_id"], ["scheduled_posts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        # A time series, not a running total: one snapshot per post per
        # collection time, so re-polling on the same tick cannot duplicate.
        sa.UniqueConstraint(
            "scheduled_post_id", "collected_at", name="uq_metric_post_collected"
        ),
    )
    op.create_index(op.f("ix_post_metrics_brand_slug"), "post_metrics", ["brand_slug"])
    op.create_index(
        op.f("ix_post_metrics_scheduled_post_id"), "post_metrics", ["scheduled_post_id"]
    )

    op.create_table(
        "post_engagements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("brand_slug", sa.String(length=64), nullable=False),
        sa.Column("scheduled_post_id", sa.Uuid(), nullable=False),
        # Denormalised from the scheduled post so the dedupe index below can be
        # scoped without a join -- ids are only unique within a platform.
        sa.Column("platform", sa.String(length=32), nullable=False),
        # `comment`, `reaction`, `share`. A string, not an enum: these arrive
        # from platform APIs that disagree about what exists, and meeting a new
        # kind should not need a migration before the row can be stored.
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("reaction_type", sa.String(length=32), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("parent_external_id", sa.String(length=128), nullable=True),
        # Often null in practice: Facebook discloses a commenter's identity only
        # to apps holding the right permissions, and reactions are usually
        # anonymous in aggregate. Store what is offered; never require it.
        sa.Column("author_external_id", sa.String(length=128), nullable=True),
        sa.Column("author_name", sa.String(length=128), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        # When the follower acted, per the platform -- nullable, because not
        # every platform says. `collected_at` is the one we can always vouch for.
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=_NOW,
            nullable=False,
        ),
        sa.Column("raw", _json(), nullable=False),
        sa.ForeignKeyConstraint(["brand_slug"], ["brands.slug"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["scheduled_post_id"], ["scheduled_posts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_post_engagements_brand_slug"), "post_engagements", ["brand_slug"]
    )
    # Polling runs overlap by design -- the same comment comes back every run --
    # so the platform's own id is what makes collection idempotent. Partial,
    # because an anonymous reaction with no id has nothing to dedupe on.
    op.create_index(
        "uq_engagement_external_id",
        "post_engagements",
        ["platform", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    # The read the agent actually makes: this post's engagement, newest first.
    op.create_index(
        "ix_engagement_post_occurred",
        "post_engagements",
        ["scheduled_post_id", "occurred_at"],
    )


def downgrade() -> None:
    # Children first: every FK here is RESTRICT or CASCADE onto the table above.
    op.drop_table("post_engagements")
    op.drop_table("post_metrics")
    op.drop_table("scheduled_posts")
    op.drop_table("approvals")
    op.drop_table("post_variants")
    op.drop_table("drafts")
    op.drop_table("brands")
